language: java
jdk:
- oraclejdk8
- openjdk8
os:
- linux
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  - provider: releases
    skip_cleanup: true
    prerelease: true
    overwrite: true
    api_key:
      secure: SpYg6TM1B2GuiV4Fitq/GjpMbEMRSk/1UWmc+0GTGH9XAsrgx6K5PhAD9bmUxDX0sBmi3PkmkpFKRZ/5PzcTvJvTad3HfC8qg84l+KTJ/1CIJQRy8Ov5a7Pej9pq3wowMdyYFMpRfe43uZkV/6hmhrUohuW1vZNsYp8rd3D1n+4LtpDNlIZfnnrvw4XEKxoQ1AT6e4+FOVL55qEBoVQxaZOTin/SBrAULMrv9p4w21Ijj1Rj/2UzaW96LCTKk6+nmMY3rapCRAXB0I2jkjOLR0UjfDrfs9seCYImk943jOvut9KIed/KY5cBI6zwUj498VL8DcLfr6iUqQZg+ca6sCEGRMd0Gu5OSb7DuzmkLT9yy3wq7lqQGmv18pSvX+FRt2vcUqmacmsBzOiuerk8rgDQrhST/+tknetHBYHgDM/7Q/7auWEq59hueH4T2x0eaZfEWdl4ik8j1UxIfQFr+WhlqwmxAsTd5Hft6SuZkjHVq3fYLnunAhbZ4MSPA81wAxCfJXRZDTCd5GdF1rHxPCUfy6iThm02r8xACWZWPnsFgZbl7n/fUHRsc/j0YewmWoFqjYXzhSEs6Wk9iDDS/6JwbeUeBi0wO2Twz00Fk1r7b1QZ9vxVHom0LKAKOUMnzyDNR+EAhd/kMMFkhjDLOu99uj2I2gJfjuT+sKdhcTY=
    file_glob: true
    file:
    - "./target/*.jar"
    - "./target/*.zip"
    on:
      repo: AdminOfThis/Util
      tags: true
  - provider: bintray
    file: "./bintray.json"
    user: "AdminOfThis"
    key:
      secure: LyxiGn1pBZgbEAya7TwndnIevC9GheSDrs2DYlp0NiXwTTmDDDzw6KT7y0K33IOq5pdp6Ww25eMmEyj88vJ+f0KgqIPamsRsVJHv1b/syzyIEhroiPUM/tNDr8GdxePyHb+WQzB5Zh2xxoUER8RXJKsLR2w5ffnL/rxI2nnjH1U/5CWSCq3TEUdVfz0uVsOV11p3P3lF3DV+TqmgWTqg9wKjZLsEjt/19+6B/2x1erfp9q9Fx0wXjllEALBrLZKw3che6MLZrCfJ1t6WqibFmxKq5YtlU085vh9MHxToq35x2mPurCI5alz3HW79wn4/Gdt8lx/5UFzrNpcabXHyDQVlwakWtt6PoWHqYx30/Zz7HUv+Rrm2rtJ7NWjF3PccTcSKOc/B4Q2HVp2d/EBZPa2SI2f6ayv8pLVh/dzhuqY3omiSL7g3sKCOLEBscm7vNvOcwYpXOFAXMbSDhEfcl3+dK5rH23HuQ6j9CfB7VdDCr45nT8IsySerFo30QTUgsqQpdc4Rlg8xkDGmlHyPkIGFjmMMcHsAG7KQVAKxB/Us2B20KwdZ/U92O8Hap1QlB34a4cioWA/nlaNr3KtMOvcAOzaqBQgbegsIxKoVolHR2M81bQJNMerbl6zzcuAksTmp09Nk6m5dbE8vdzd0EeyM8KfRygmSt5i9d2Y669Y=
    skip_cleanup: true # to upload artifacts created during the build